### ISSUE TITLE
Add support for RE-HLDS and ReGameDLL_CS

### ISSUE THREAD

**Issue by SmileYzn** [Arkshine/CSBotEnabler#3]
Add support for RE-HLDS and ReGameDLL_CS

This is a n1ce bot feature anyway.

**Comment by Arkshine** [comment]
https://github.com/s1lentq/ReGameDLL_CS#how-to-install-zbot-for-cs-16

**Comment by SmileYzn** [comment]
Ops sorry, i hope that is only for normal hlds
